---
redis_version: 3.0.2
redis_user: redis
redis_install_dir: /opt/redis
redis_dir: /var/lib/redis/{{ redis_port }}
redis_bind: 0.0.0.0
redis_port: 6379
redis_logfile: /var/log/redis/{{ redis_port }}.log
redis_pidfile: /var/run/redis/{{ redis_port }}.pid
redis_log_level: notice

redis_password: false
redis_nofile_limit: 16384

redis_syslog_enabled: "yes"
redis_syslog_facility: USER

redis_slave_of: false

redis_sentinel: false
redis_sentinel_port: 26379
redis_sentinel_bind: 0.0.0.0
redis_sentinel_syslog_ident: redis_sentinel{{ redis_sentinel_port }}
redis_sentinel_pidfile: /var/run/redis/sentinel{{ redis_sentinel_port }}.pid
redis_sentinel_dir: /var/lib/redis/sentinel_{{ redis_sentinel_port }}
redis_sentinel_log_file: /var/log/redis/sentinel_{{ redis_sentinel_port }}.log
redis_sentinel_monitors:
  - name: master01
    host: 127.0.0.1
    port: 6379
    quorum: 1
    auth_pass: ant1r3z
    down_after_milliseconds: 30000
    parallel_syncs: 1
    failover_timeout: 30000
    notification_script: false
    client_reconfig_script: false