---

- name: install epel
  yum: name=http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm state=present

- name: install nginx
  yum: name=nginx state=present

- name: add nginx start on boot
  shell: /sbin/chkconfig --add nginx

- name: turn on nginx start on boot
  shell: /sbin/chkconfig nginx on

- name: create log directory
  file: path=/var/logs/nginx state=directory owner=nginx group=nginx mode=0755

- name: create enable site directory
  file: path=/etc/nginx/sites_enabled state=directory owner=nginx group=nginx mode=0755

- name: copy conf
  copy: src={{item}} dest=/etc/nginx/sites_enabled/{{item| regex_replace('^.*/nginx/files/(.*\.conf)$', '\\1')}} force=yes
  with_fileglob:
    - ./*


- name: config nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: flush handlers to apply config changes
  meta: flush_handlers

- name: ensure nginx is running
  service: name=nginx state=started